//LOCAL
###
GET http://localhost:3001/adminPrestatario/ HTTP/1.1
Content-Type: application/json

//Peticion obtener prestatario por ID
###
GET http://localhost:3001/adminPrestatario/63d41ecec22069c376bed6af HTTP/1.1
Content-Type: application/json

//Peticion obtener prestatatario por idPrestatario
###
GET http://localhost:3001/adminPrestatario/idPrestatario/1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/adminPrestatario/idPrestatario/2 HTTP/1.1
Content-Type: application/json







//Railway
//Petición obtener todos los prestatarios
###
GET https://softni-syncprestatario-production.up.railway.app/adminPrestatario/ HTTP/1.1
Content-Type: application/json

//Railway
//Petición obtener prestatario por ID
###
GET https://softni-syncprestatario-production.up.railway.app/adminPrestatario/63d41ecec22069c376bed6af HTTP/1.1
Content-Type: application/json

//Railway
//Petición obtener prestatatario por idPrestatario
###
GET https://softni-syncprestatario-production.up.railway.app/adminPrestatario/idPrestatario/1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/adminPrestatario/idPrestatario/2 HTTP/1.1
Content-Type: application/json


//Vercel

###
GET https://softni-sync-prestatario-edgarvrp.vercel.app/adminPrestatario/ HTTP/1.1
Content-Type: application/json


###
GET https://softni-sync-prestatario.vercel.app/adminPrestatario/63d41ecec22069c376bed6af HTTP/1.1
Content-Type: application/json

###
GET https://softni-sync-prestatario-edgarvrp.vercel.app/adminPrestatario/idPrestatario/2 HTTP/1.1
Content-Type: application/json